
spring:
  application:
    #应用名，也是Eureka的服务名
    name: cosumer

server:
  port: 8088

eureka:
  client:
    #注册中心地址
    serviceUrl:
      #注册中心独立模式
      #defaultZone: http://localhost:8090/eureka/
      #注册中心点对点模式
      defaultZone: http://peer1.com:8091/eureka/,http://peer2.com:8092/eureka/,http://peer3.com:8093/eureka/

