spring:
  application:
    name: ureka-client-gateway
  cloud:
    gateway:
      routes:
        - id: cosumer-1
          uri: lb://cosumer
          predicates:
            - Path=/testGets
            - Before=2023-06-28T00:01:26.099+08:00[Asia/Shanghai]

    #gateway:
      #routes[0]:
        #id: cosumer-1
        #uri:  lb://cosumer
        #predicates[0]: Path=/testGets
        #filters[0]: PrefixPath=/testGets

      #routes[1]:
        #id: cosumer-2
        #uri:  lb://cosumer
        #predicates:
          #Path=/testGet

      discovery:
        locator:
          enabled:  true

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1.com:8091/eureka/,http://peer2.com:8092/eureka/,http://peer3.com:8093/eureka/

server:
  port: 9000