
spring:
  application:
    #应用名，也是Eureka的服务名
    name: config-server
  profiles:
    active: native

server:
  port: 1002

eureka:
  client:
    #注册中心地址
    serviceUrl:
      defaultZone: http://peer1.com:8091/eureka/,http://peer2.com:8092/eureka/,http://peer3.com:8093/eureka/


